name: Publish Website (Test)

on:
  push:
    branches:
      - astro-refactoring

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server:   ${{ secrets.FTP_STEPHANBOGNER_SERVER   }}
        ftp-username: ${{ secrets.FTP_STEPHANBOGNER_USERNAME }}
        ftp-password: ${{ secrets.FTP_STEPHANBOGNER_PASSWORD }}
        local-dir: ./build/
        git-ftp-args: --lock