name: Publish Website

on:
  push:
    branches:
      - production

jobs:
  upload-build:
    name: Upload build
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: 🚀 Sync to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server:   ${{ secrets.FTP_SERVER   }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        git-ftp-args: --lock